# Library 

In [129]:
import numpy as np
P=np.array([ [
    [0.3,0.25,0.2,0.15,0.1],
     [0,0.3,0.3,0.25,0.15],
     [0,0,0.35,0.45,0.2],
     [0,0,0,0.5,0.5],
     [0,0,0,0,1]],
 
   [[1,0,0,0,0],
     [0.8,0.2,0,0,0],
     [0.7,0.2,0.1,0,0],
     [0.6,0.25,0.1,0.05,0],
     [0.5,0.25,0.05,0.15,0.05]]])



R =np.array([ 
    [0,-1],
     [0,-3],
     [-1,-5],
     [-8,-5],
     [-40,-8] ])
print(P)
print(R)

[[[0.3  0.25 0.2  0.15 0.1 ]
  [0.   0.3  0.3  0.25 0.15]
  [0.   0.   0.35 0.45 0.2 ]
  [0.   0.   0.   0.5  0.5 ]
  [0.   0.   0.   0.   1.  ]]

 [[1.   0.   0.   0.   0.  ]
  [0.8  0.2  0.   0.   0.  ]
  [0.7  0.2  0.1  0.   0.  ]
  [0.6  0.25 0.1  0.05 0.  ]
  [0.5  0.25 0.05 0.15 0.05]]]
[[  0  -1]
 [  0  -3]
 [ -1  -5]
 [ -8  -5]
 [-40  -8]]


In [130]:
import mdptoolbox, mdptoolbox.example
pi = mdptoolbox.mdp.PolicyIteration(P, R, 0.75)
pi.run()
print(pi.policy)
print(pi.V)
print(pi.iter)

(1, 0, 0, 1, 1)
(-3.9999999999999942, -6.273247087846309, -7.963143761336942, -8.90750089461969, -12.443579813678994)
2


In [131]:
rvi = mdptoolbox.mdp.ValueIteration(P, R,0.75)
rvi.run()
print(rvi.policy)
print(rvi.V)
print(rvi.iter)

(1, 0, 0, 1, 1)
(-3.831059455871582, -6.100998320282544, -7.791506863980537, -8.736977070413575, -12.272907759744445)
12
